### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-05-18/lcolsant#1]
https://github.com/CodingDojo-MEAN-05-18/lcolsant/blob/ca4db6f2d188fb700511b8f7a905bb48ef42d3bf/Angular/github-score/src/app/task.service.ts#L14-L19

Sending errors on an Observable you can call the `error` method. 
`(error) => this.tasks.error(error)`

If you're going to use BehaviorSubjects in your services to send data then you probably want two. One for 'valid' data and another for invalid/error handling. 

See this SO **answer**: https://stackoverflow.com/questions/41827371/how-do-i-throw-an-error-on-a-behaviour-subject-and-continue-the-stream

**Comment by lcolsant** [comment]
Hi Jason - I added an additional behviorSubject to handle the errors.  I'm still getting some errors though.  Can you please take another look.  I've pushed the updated code to the same repo.  thanks.

**Comment by dojo-json** [comment]
```typescript 
  gitData(username: string) {
    this._http.get(
      `https://api.github.com/users/${username}`
    )
    .subscribe(
      data => this.handleData(data as any),
      errors => this.handleErrors(errors as any));
  }

  handleData(data: any[]) {
    // this.errors.next(null);
    this.tasks.next(data);  //success path
  }

  handleErrors(error: any[]) {
    this.errors.next(error); //error path
    // this.tasks.next(null);
  }
```

Those errors were a result of context (`this`) not being the service object you expected it to be. When passing the method directly as the callback it disassociates it from the current object and it takes on the context of the caller (Subscriber in this case). 

Consider the above code and how it fixes this issue. I would also note that using `any` is generally a bad idea and defeats one of the main benefits of TypeScript: strong types. I recommend transforming `any` into something more appropriate. Describe your data, perhaps as a `GithubUser` interface or a string for errors?

Let me know if this helps.

**Comment by lcolsant** [comment]
Great, thanks Jason! This fixed the issue.
