### ISSUE TITLE
dojo-weather-forecast app; issue with .map

### ISSUE THREAD

**Issue by lcolsant** [CodingDojo-MEAN-05-18/lcolsant#2]
Hi Jason - I'm getting an error message when using .map() on line 19 of weather.service.ts file.  I tried several import statements on lines 5-7 but they did not resolve the issue.
```
 getWeather(location: string){
    let apiKey = 'ab93560c3c304c6be78da42e40565e12';
    return this.http.get(`http://api.openweathermap.org/data/2.5/weather?q=${location}&units=imperial&&appid=${apiKey}`)
    .map( data => data.json() )
    .toPromise()  //do we need this line?
  }
```
Import statements not working...
`import 'rxjs';`
`import 'rxjs/add/operator/map';`
`import 'rxjs/Rx';`

Also wondering why .toPromise() is necessary on line 20? This is in the HW solution.

My repo is below:
[https://github.com/CodingDojo-MEAN-05-18/lcolsant/tree/master/Angular/dojo-weather-forecast](url)

thanks,
Lee

**Comment by lcolsant** [comment]
This was resolved during code review today. Thanks for the help!!  I completed the remainder and final version can be found here:
https://github.com/CodingDojo-MEAN-05-18/lcolsant/tree/master/Angular/dojo-weather-forecast

thanks,
Lee

**Comment by dojo-json** [comment]
I'm pleased that you tagged me, but I did not see this until much later. You've prompted me to seek ways to be more aware of these notifications. Appreciate it.

**Comment by lcolsant** [comment]
no worries! For the remainder of the course, I'll shoot you an email when I
open a case.  Appreciate the help to get through the final push. #exhausted
