### ISSUE TITLE
Project Product Management

### ISSUE THREAD

**Issue by lcolsant** [CodingDojo-MEAN-05-18/lcolsant#3]
Hi Jason - can you please take a look at line 37 of product-new.component.ts? I am attempting to push a new product object to the 'products' array and it is throwing out an error.

https://github.com/CodingDojo-MEAN-05-18/lcolsant/tree/master/Angular/project-product-managment
` this.products.push(this.newProduct);  //Erroring out here!!!`

Thanks,
Lee

**Comment by dojo-json** [comment]
https://github.com/CodingDojo-MEAN-05-18/lcolsant/blob/a46463c9f72d8344717062800bb516b485b79726/Angular/project-product-managment/src/app/product.service.ts#L9-L11

What is `this.products` when you attempt to push? Consider your initial value to your productsObservable `BehaviorSubject`.

**Comment by lcolsant** [comment]
Got it! That code really does what you tell it to do. :-)  thanks
