### ISSUE TITLE
anonymous notes - add note redirect

### ISSUE THREAD

**Issue by lcolsant** [CodingDojo-MEAN-05-18/lcolsant#5]
Hi Jason - when I add a new note, the note successfully posts to the DB now, but I still need to refresh the page manually for it to show in the notes-list component.  In my note-create component, I have a redirect to home on line 45:
`this.router.navigateByUrl('/');`

but it does not trigger a refresh for my note-list component. If, however, I redirect to my note-list component only:

`this.router.navigateByUrl('noteList');` 
it does work. However, from the assignment, both components are showing on the same page at the same time.

https://github.com/CodingDojo-MEAN-05-18/lcolsant/tree/master/Angular/anonymous-notes

Thanks,
Lee

**Comment by dojo-json** [comment]
I would suggest that routing may not be necessary for this assignment. Or, if implemented simply load the home (or note-list) into the outlet. With that said, your current architecture with create nested inside your list works well. The router on a redirect/navigate will examine the current url and the new url. If they are the same there is no change, the components do not reload. 

Instead of attempting to navigate, utilize `@output` to send data to a parent. Your create component really doesn't need to know all the notes that exist. It just needs to know how to create a new one and send that information elsewhere for processing. (Consider our smart/presentational discussion)

**Comment by lcolsant** [comment]
thanks Jason.  I eliminated the router and utilized @output to send a new note from note-create component to note-list component.  I am getting an error message (related to my passingNote function on app.component).  Can you please take a look? My code has been pushed.

**Comment by dojo-json** [comment]
Whats the error message? Also, just an FYI. When using `@` encapsulate it in back ticks, otherwise it will tag the Github username `output`. Amusing, maybe not for them though.

**Comment by lcolsant** [comment]
i get the following error message below. I think it is because the function passingNote() is on my note-list component and not on app-component. But I need the function and the passed note object to go to note-list. I'm not sure how to fix this.

![image](https://user-images.githubusercontent.com/24836854/42402030-4e98dde8-812d-11e8-9d77-06f6e6442487.png)

**Comment by dojo-json** [comment]
It appears you do not have a method on your app component to handle emitted notes. Also, I would consider moving the `emitNote` inside your Observable subscription. You want to send the note from the database, not the information from the form.

**Comment by dojo-json** [comment]
Consider the app component is the parent and should handle adding new content to the array of notes (remove all arrays of things from create note component). Once that array is updated you should pass it to any children (the list). The default change detection handles this rather well.

**Comment by lcolsant** [comment]
Sorry...not sure i follow.  If i have the passingNote function on app component, how will i be able to pass the new note object to note-list component.

**Comment by dojo-json** [comment]
The `passingNote` method does not exist on the app.component that I see.

https://github.com/CodingDojo-MEAN-05-18/lcolsant/blob/edfe30e8d19f00e1b454035cb7e7ef6f2748abba/Angular/anonymous-notes/src/app/app.component.ts#L1-L10

Once you add the new note from the database to the array of notes on your app component Angular's change detection will update the needed components/content.

**Comment by lcolsant** [comment]
Why do I need to bring everything inside of app component?  I thought that I would be able to pass data between two standalone components (i.e. from app-create to app-list)?  Apologies for all of the back and forth.  Is there a time we can discuss whether it be this week or next?

**Comment by dojo-json** [comment]
You can not pass data between siblings. Only parent-child relationships can pass data. You don't necessarily need to pass to your app component. You can nest your `app-create` inside your `app-list` and pass data to it. Your current setup is `create` and `list` are children of `app.component`. Modify so `list` is the only child to `app` and `create` is  a child to `list`. Then it will work as you desire.

**Comment by lcolsant** [comment]
ok thanks. I am now using app component as the parent of the two. I was able to `@output` to app component and console log successfully.  However, not sure the note object is coming through `@input` on note-list component.  I added it to my note-list html (lines 3-5) and nothing shows.

I believe i have it config properly
`<div class="container">`
 ` <h1>Anonymous Notes</h1>`
  `<app-note-create (emitNote)="dataFromChild($event)"></app-note-create>`
 ` <app-note-list [myNewNotes]="myNotes"></app-note-list>`
`</div>`

Whenever you get a chance...new code has been pushed.  thanks.
