### ISSUE TITLE
bicycle-marketplace - registration errors

### ISSUE THREAD

**Issue by lcolsant** [CodingDojo-MEAN-05-18/lcolsant#7]
Hi Jason - i'm getting some errors below when i try to register my user object to the db.  I know that it is coming across from the form ok as you can see from the console log.  But using the api does not work.
Can you please take a look?  
thanks, lee

![regerror1](https://user-images.githubusercontent.com/24836854/42655528-4e1c3bc8-85d1-11e8-98fa-66de816e088f.PNG)

![regerror2](https://user-images.githubusercontent.com/24836854/42655538-50ac1ec6-85d1-11e8-9f4b-cd706288fe29.PNG)

https://github.com/CodingDojo-MEAN-05-18/lcolsant/tree/master/Angular/bicycle-marketplace

**Comment by dojo-json** [comment]
Remember that middleware is executed in the order it is defined. The problem is located in `server.js`. Consider how you are `use`ing your middleware.

**Comment by lcolsant** [comment]
tricky tricky ;-)   thanks Jason!
